import '../models/doctor.dart';
import '../models/patient.dart';
import '../models/appointment.dart';
import '../models/consultation.dart';
import '../models/vital_signs.dart';
import '../models/prescription.dart';

class MockDataService {
  static List<Doctor> getDoctors() {
    return [
      Doctor(
        id: 'doc_1',
        name: 'د. أحمد منصور',
        title: 'استشاري أول الأمراض الباطنية والسكر',
        specialty: 'الأمراض الباطنية',
        roomNumber: 'عيادة 101',
        consultationFee: 300.0,
        followUpFee: 100.0,
        phone: '01012345678',
        availableDays: ['السبت', 'الأحد', 'الاثنين', 'الأربعاء'],
        workingHours: '04:00 م - 10:00 م',
        avatarColorValue: 0xFF0F766E,
        rating: 4.9,
      ),
      Doctor(
        id: 'doc_2',
        name: 'د. سارة عبد الرحمن',
        title: 'أخصائية طب الأطفال وحديثي الولادة',
        specialty: 'طب الأطفال',
        roomNumber: 'عيادة 102',
        consultationFee: 250.0,
        followUpFee: 100.0,
        phone: '01123456789',
        availableDays: ['يومياً ماعدا الجمعة'],
        workingHours: '02:00 م - 08:00 م',
        avatarColorValue: 0xFF0284C7,
        rating: 4.95,
      ),
      Doctor(
        id: 'doc_3',
        name: 'د. خالد الشناوي',
        title: 'استشاري جراحة العظام والعمود الفقري',
        specialty: 'جراحة العظام',
        roomNumber: 'عيادة 103',
        consultationFee: 350.0,
        followUpFee: 150.0,
        phone: '01234567890',
        availableDays: ['السبت', 'الثلاثاء', 'الخميس'],
        workingHours: '06:00 م - 11:00 م',
        avatarColorValue: 0xFF6366F1,
        rating: 4.85,
      ),
      Doctor(
        id: 'doc_4',
        name: 'د. مريم يوسف',
        title: 'استشارية الأمراض الجلدية والليزر',
        specialty: 'الجلدية والتجميل',
        roomNumber: 'عيادة 104',
        consultationFee: 300.0,
        followUpFee: 100.0,
        phone: '01512345678',
        availableDays: ['الأحد', 'الاثنين', 'الأربعاء'],
        workingHours: '03:00 م - 09:00 م',
        avatarColorValue: 0xFFEC4899,
        rating: 4.9,
      ),
      Doctor(
        id: 'doc_5',
        name: 'د. طارق إبراهيم',
        title: 'استشاري طب وجراحة العيون والليزك',
        specialty: 'طب العيون',
        roomNumber: 'عيادة 105',
        consultationFee: 320.0,
        followUpFee: 120.0,
        phone: '01098765432',
        availableDays: ['السبت', 'الاثنين', 'الأربعاء'],
        workingHours: '05:00 م - 10:00 م',
        avatarColorValue: 0xFF059669,
        rating: 4.8,
      ),
    ];
  }

  static List<Patient> getPatients() {
    final now = DateTime.now();

    return [
      Patient(
        id: 'pat_1',
        patientCode: 'PAT-1001',
        name: 'محمد إبراهيم حسن',
        age: 48,
        gender: Gender.male,
        phone: '01001122334',
        nationalId: '27608151234567',
        bloodGroup: 'O+',
        chronicDiseases: ['السكري من النوع الثاني', 'ارتفاع ضغط الدم'],
        allergies: ['البنسلين (Penicillin)'],
        notes: 'المريض يتابع بانتظام كل شهرين لفحص السكر التراكمي.',
        registeredAt: now.subtract(const Duration(days: 120)),
        medicalHistory: [
          Consultation(
            id: 'cons_1',
            patientId: 'pat_1',
            doctorId: 'doc_1',
            doctorName: 'د. أحمد منصور',
            doctorSpecialty: 'الأمراض الباطنية',
            date: now.subtract(const Duration(days: 45)),
            chiefComplaint: 'صداع متكرر وإرهاق عام وزيادة في العطش',
            clinicalExamination: 'الصدر والبطن طبيعيان، يوجد وذمة خفيفة في الأطراف السفلية.',
            diagnosis: 'عدم انتظام سكر الدم وارتفاع طفيف في ضغط الدم الشرياني',
            vitals: VitalSigns(
              systolicBp: '145',
              diastolicBp: '92',
              pulse: '78',
              temperature: '37.1',
              bloodSugar: '185',
              weight: '86',
              height: '176',
              spO2: '98',
              recordedAt: now.subtract(const Duration(days: 45)),
            ),
            prescription: Prescription(
              id: 'rx_1',
              doctorName: 'د. أحمد منصور',
              doctorSpecialty: 'الأمراض الباطنية',
              patientName: 'محمد إبراهيم حسن',
              date: now.subtract(const Duration(days: 45)),
              items: [
                PrescriptionItem(
                  medicineName: 'Janumet 50/1000mg',
                  dosage: 'قرص واحد',
                  frequency: 'مرتين يومياً بعد الوجبات',
                  duration: 'لمدة شهرين',
                  instructions: 'مع الالتزام بالحمية الغذائية قليلة السكريات',
                ),
                PrescriptionItem(
                  medicineName: 'Concor 5mg',
                  dosage: 'قرص واحد',
                  frequency: 'مرة واحدة صباحاً',
                  duration: 'مستمر',
                  instructions: 'يؤخذ على الريق يومياً',
                ),
              ],
            ),
            labTestsRequested: ['تحليل سكر تراكمي HbA1c', 'وظائف كلى وفحص بول كامل'],
            followUpDate: now.add(const Duration(days: 15)),
            notes: 'تحسن ملحوظ في قياسات الضغط مقارنة بالزيارات السابقة.',
          ),
        ],
      ),
      Patient(
        id: 'pat_2',
        patientCode: 'PAT-1002',
        name: 'فاطمة محمود علي',
        age: 32,
        gender: Gender.female,
        phone: '01122334455',
        nationalId: '29204011234568',
        bloodGroup: 'A+',
        chronicDiseases: ['حساسية الصدر (الربو)'],
        allergies: ['السلفا (Sulfa)'],
        notes: 'تستخدم بخاخ وقائي بانتظام في مواسم تغير الفصول.',
        registeredAt: now.subtract(const Duration(days: 90)),
        medicalHistory: [
          Consultation(
            id: 'cons_2',
            patientId: 'pat_2',
            doctorId: 'doc_1',
            doctorName: 'د. أحمد منصور',
            doctorSpecialty: 'الأمراض الباطنية',
            date: now.subtract(const Duration(days: 20)),
            chiefComplaint: 'ضيق في التنفس وسعال جاف ليلي',
            clinicalExamination: 'أصوات أزيز خفيف في الرئتين عند الزفير.',
            diagnosis: 'نوبة ربو خفيفة محفزة بتغير الطقس',
            vitals: VitalSigns(
              systolicBp: '118',
              diastolicBp: '76',
              pulse: '84',
              temperature: '36.8',
              bloodSugar: '95',
              weight: '62',
              height: '164',
              spO2: '97',
              recordedAt: now.subtract(const Duration(days: 20)),
            ),
            prescription: Prescription(
              id: 'rx_2',
              doctorName: 'د. أحمد منصور',
              doctorSpecialty: 'الأمراض الباطنية',
              patientName: 'فاطمة محمود علي',
              date: now.subtract(const Duration(days: 20)),
              items: [
                PrescriptionItem(
                  medicineName: 'Ventolin Inhaler 100mcg',
                  dosage: 'بختين',
                  frequency: 'عند اللزوم / كل 6 ساعات',
                  duration: 'لمدة أسبوعين',
                ),
                PrescriptionItem(
                  medicineName: 'Symbicort Turbuhaler 160/4.5',
                  dosage: 'استنشاق واحد',
                  frequency: 'مرتين يومياً صباحاً ومساءً',
                  duration: 'لمدة شهر',
                ),
              ],
            ),
            labTestsRequested: ['أشعة عادية على الصدر X-Ray'],
          ),
        ],
      ),
      Patient(
        id: 'pat_3',
        patientCode: 'PAT-1003',
        name: 'يوسف كريم السيد',
        age: 7,
        gender: Gender.male,
        phone: '01233445566',
        nationalId: '31705121234569',
        bloodGroup: 'B+',
        chronicDiseases: [],
        allergies: [],
        notes: 'الطفل مطعم بكافة التطعيمات الإلزامية حتى عمره الحالي.',
        registeredAt: now.subtract(const Duration(days: 60)),
        medicalHistory: [
          Consultation(
            id: 'cons_3',
            patientId: 'pat_3',
            doctorId: 'doc_2',
            doctorName: 'د. سارة عبد الرحمن',
            doctorSpecialty: 'طب الأطفال',
            date: now.subtract(const Duration(days: 10)),
            chiefComplaint: 'ارتفاع في درجة الحرارة ورشح وألم بالحلق',
            clinicalExamination: 'احتقان بالبلعوم وتضخم خفيف في اللوزتين.',
            diagnosis: 'التهاب فيروسي بالحلق والجهاز التنفسي العلوي',
            vitals: VitalSigns(
              systolicBp: '100',
              diastolicBp: '65',
              pulse: '98',
              temperature: '38.4',
              weight: '24',
              height: '122',
              spO2: '99',
              recordedAt: now.subtract(const Duration(days: 10)),
            ),
            prescription: Prescription(
              id: 'rx_3',
              doctorName: 'د. سارة عبد الرحمن',
              doctorSpecialty: 'طب الأطفال',
              patientName: 'يوسف كريم السيد',
              date: now.subtract(const Duration(days: 10)),
              items: [
                PrescriptionItem(
                  medicineName: 'Cetal Suspension 250mg',
                  dosage: '5 مل',
                  frequency: 'كل 6 ساعات عند ارتفاع الحرارة',
                  duration: 'لمدة 4 أيام',
                ),
                PrescriptionItem(
                  medicineName: 'Physiomer Baby Spray',
                  dosage: 'بخة واحدة في كل فتحة أنف',
                  frequency: '3 مرات يومياً قبل النوم والرضاعة',
                  duration: 'لمدة 5 أيام',
                ),
              ],
            ),
          ),
        ],
      ),
      Patient(
        id: 'pat_4',
        patientCode: 'PAT-1004',
        name: 'طارق عبد الله مرسي',
        age: 55,
        gender: Gender.male,
        phone: '01044556677',
        nationalId: '26911201234570',
        bloodGroup: 'AB+',
        chronicDiseases: ['خشونة في مفصل الركبة اليمنى'],
        allergies: [],
        notes: 'يعاني من صعوبة في صعود السلالم منذ شهرين.',
        registeredAt: now.subtract(const Duration(days: 30)),
      ),
      Patient(
        id: 'pat_5',
        patientCode: 'PAT-1005',
        name: 'نادية مصطفى كامل',
        age: 27,
        gender: Gender.female,
        phone: '01155667788',
        nationalId: '29703141234571',
        bloodGroup: 'O-',
        chronicDiseases: [],
        allergies: [],
        notes: 'كشف لمتابعة تساقط الشعر ونضارة البشرة.',
        registeredAt: now.subtract(const Duration(days: 15)),
      ),
    ];
  }

  static List<Appointment> getAppointments() {
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);

    return [
      Appointment(
        id: 'apt_1',
        patientId: 'pat_1',
        patientName: 'محمد إبراهيم حسن',
        patientPhone: '01001122334',
        doctorId: 'doc_1',
        doctorName: 'د. أحمد منصور',
        specialty: 'الأمراض الباطنية',
        dateTime: today.add(const Duration(hours: 17, minutes: 0)),
        tokenNumber: 1,
        visitType: VisitType.followUp,
        status: AppointmentStatus.inConsultation,
        fee: 100.0,
        notes: 'متابعة نتائج السكر التراكمي وتعديل جرعة الدواء.',
      ),
      Appointment(
        id: 'apt_2',
        patientId: 'pat_2',
        patientName: 'فاطمة محمود علي',
        patientPhone: '01122334455',
        doctorId: 'doc_1',
        doctorName: 'د. أحمد منصور',
        specialty: 'الأمراض الباطنية',
        dateTime: today.add(const Duration(hours: 17, minutes: 30)),
        tokenNumber: 2,
        visitType: VisitType.followUp,
        status: AppointmentStatus.waiting,
        fee: 100.0,
        notes: 'استشارة بعد الأشعة العادية للصدر.',
      ),
      Appointment(
        id: 'apt_3',
        patientId: 'pat_3',
        patientName: 'يوسف كريم السيد',
        patientPhone: '01233445566',
        doctorId: 'doc_2',
        doctorName: 'د. سارة عبد الرحمن',
        specialty: 'طب الأطفال',
        dateTime: today.add(const Duration(hours: 15, minutes: 0)),
        tokenNumber: 1,
        visitType: VisitType.newVisit,
        status: AppointmentStatus.completed,
        fee: 250.0,
        notes: 'كشف دوري ونزلة برد.',
      ),
      Appointment(
        id: 'apt_4',
        patientId: 'pat_4',
        patientName: 'طارق عبد الله مرسي',
        patientPhone: '01044556677',
        doctorId: 'doc_3',
        doctorName: 'د. خالد الشناوي',
        specialty: 'جراحة العظام',
        dateTime: today.add(const Duration(hours: 18, minutes: 30)),
        tokenNumber: 1,
        visitType: VisitType.newVisit,
        status: AppointmentStatus.waiting,
        fee: 350.0,
        notes: 'ألم مستمر في الركبة اليمنى عند المشي.',
      ),
      Appointment(
        id: 'apt_5',
        patientId: 'pat_5',
        patientName: 'نادية مصطفى كامل',
        patientPhone: '01155667788',
        doctorId: 'doc_4',
        doctorName: 'د. مريم يوسف',
        specialty: 'الجلدية والتجميل',
        dateTime: today.add(const Duration(hours: 16, minutes: 0)),
        tokenNumber: 1,
        visitType: VisitType.newVisit,
        status: AppointmentStatus.waiting,
        fee: 300.0,
        notes: 'جلسة استشارة جلدية.',
      ),
    ];
  }
}
